### ISSUE TITLE
express-handlebars viewing engine support

### ISSUE THREAD

**Issue by DJviolin** [Siedrix/paperpress#7]
I'm trying to build my personal photography website with express.js and [express-handlebars](https://www.npmjs.com/package/express-handlebars) templating engine. I use mainly the built-in routing capabilities of express, however it would be nice to have a blog with content separated pages and maybe categories, tags support.

I feel many static generators an overkill, I searched some lightweight option and this is when I found your project!

You can see my work here: https://github.com/DJviolin/horgalleryNode

In `routes/journal.js` you can see the Paperpress implementation. I trying to only effect the `/journal` route with Paperpress, leaving everything else untouched (for the other pages express' built-in router is enough), but I want to share between them the handlebars templates at `views` folder.

I renamed every .hbs files to .html in favour of Paperpress, because it's looking after .html files. Is there a way to choose somehow the viewing engine?

Also, can I define the layout file names? For example, If I want the main layout file at `views/paperpress/journal.html`?

Can I set paperpress to use the handlebars templates at `view` folder?

**Comment by Siedrix** [comment]
I know its late and you probably don't need it anymore, but the new version of Paperpress already has this changes. Its decouple from express and swig.

The releases on 0.9.x are the road to v1.0, so its probably better to wait a little more to have a stable API. I might change a couple of thing before the final release.

**Comment by DJviolin** [comment]
Thank You! Yes, I built my own static blog. I reading the blog posts from a single json file with fs, so not using markdown from different folders (I not decided yet which is better). I try to make database ready my site when I will be able to integrate with a db. The actual project is here: https://github.com/DJviolin/lantosistvan
